config/routes.rb
Rails.application.routes.draw do
  resources :word_counters, only: [:index, :create]
  resources :word_statistics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word_counter.rb
class WordCounter < ApplicationRecord
end

app/models/word_statistic.rb
class WordStatistic < ApplicationRecord

    def self.search(search)
        if search
            self.where(word: search)
        else
            WordStatistic.all
        end 
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/word_counters_controller.rb
require 'open-uri'

class WordCountersController < ApplicationController
	
	def new
		@word_counters = WordCounters.new
	end
	
	# Update the count for each word in an input
	# It handles strings, files and URL data
	def create
		input = params[:word_counter][:input]
		
		# Checking if the input is a URL and getting its content
		if(helpers.uri?(input))
			helpers.process_url(input) 
		# Check if the string is a file path
		elsif File.file?(input)					
			helpers.count_words_in_file(input)
		else
			helpers.count_words_in_string(input)
		end
		redirect_to :controller => 'word_counters', :action => 'index', notice: 'Word statistic was successfully created.'
		
	end

	def word_counter_params
		params.permit(:input)
	end

end

app/controllers/word_statistics_controller.rb
class WordStatisticsController < ApplicationController
	
	# If a user searches for a word then this function is called
	def index
	@word_statistics =  WordStatistic.search(word_statistic_params[:search])
	end	

	# Show word by its name through an API call 
	def show 
		requested_word = params[:id]
		fetched_word = WordStatistic.where(word: requested_word).first
		if fetched_word.nil?
			render json: {status: 'ERROR',message: 'word ' + requested_word + ' was not saved yet'}, status: :unprocessable_entity
		else
			render json: {status: 'SUCCESS',message: 'count of a word ' + requested_word + ' ', data: fetched_word.count}, status: :ok
		end 
	end	
	
	# Delete by word by ID
	def destroy
		word = WordStatistic.find(params[:id])
		word.destroy
		render json: {status: 'SUCCESS',message: 'word was deleted'}, status: :ok 
	end

	private

	def word_statistic_params
		params.permit(:word, :count, :search)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/word_counters_helper.rb
module WordCountersHelper
    
    # Count word appearances amount in a given string and save to db
    def count_words_in_string(string)
        words = string.split(' ')
        for word in words do
            word.downcase!
            word_stats = WordStatistic.where(word: word).first
                if !word_stats.nil?
                    word_stats.count+=1
                    word_stats.save!
                else
                    WordStatistic.create(word: word, count: 1)
                end
            end
    end

    def count_words_in_file(file_path)
        file = File.open(file_path, "r")
        file.each_line { |line| count_words_in_string(line)}
    end

    # Checking if the string is a URL
    def uri?(string)
        uri = URI.parse(string)
        %w( http https ).include?(uri.scheme)
        rescue URI::BadURIError
        false
        rescue URI::InvalidURIError
        false
    end

    # Get the URL
    def process_url(input)
        page_content = open(input) { 
            |io| data = io.read
            count_words_in_string(data)
            }
        end    
    
    end

app/helpers/word_statistics_helper.rb
module WordStatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeTask</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "style.css" %>
  </head>

  <body>
    <div class="header">
      <div class="logo">Hello There!</div>
      <div>
        <%= link_to 'Words List', word_statistics_path %>
      </div>
      <div>
        <%= link_to 'Insert a new input', word_counters_path %>
      </div>
    </div>
    <div class="app-body">
    <h1>Count on us to count your words</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/word_counters/_form.html.erb
<%= form_for(word_counter) do |f| %>
  <% if word_counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_counter.errors.count, "error") %> prohibited this word_counter from being saved:</h2>

      <ul>
      <% word_counter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :input %>
    <%= f.text_field :input %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/word_counters/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Your words are important to us</h3>

<%= form_for :word_counter, url: word_counters_path do |f|  %>
<div class="form-container">
   <%= f.text_field :input ,placeholder: "Enter text, file path or a URL...", :class => 'text-input'%>
   <%= f.submit "Count" , :class => 'submit-button'%> 
   </div>
<% end %>
<br>


app/views/word_statistics/_form.html.erb
<%= form_for(word_statistic) do |f| %>
  <% if word_statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_statistic.errors.count, "error") %> prohibited this word_statistic from being saved:</h2>

      <ul>
      <% word_statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :count %>
    <%= f.number_field :count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/word_statistics/index.html.erb
<p id="notice"><%= notice %></p>


<h3>Search or browse the list below to see how many times a word appeared so far</h3>
 
  <%= form_tag(word_statistics_path, method: :get,:class=>"form-container") do %>
    <%= text_field_tag(:search, params[:search],:class=>"text-input")%>
      <%= submit_tag("Go", :class=>"submit-button") %>
      <% end %>
<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Count</th>
     </tr>
  </thead>

  <tbody>
    <% @word_statistics.each do |word_statistic| %>
      <tr>
        <td><%= word_statistic.word %></td>
        <td><%= word_statistic.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Go ahead and add more words!', word_statistics_path %>

app/views/word_statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word_statistic.word %>
</p>

<p>
  <strong>Count:</strong>
  <%= @word_statistic.count %>
</p>

<%= link_to 'Edit', edit_word_statistic_path(@word_statistic) %> |
<%= link_to 'Back', word_statistics_path %>